services:
  lavalink:
    build: lavalink_server
    volumes:
      - ./data/lavalink:/opt/Lavalink/logs
    command: java -jar Lavalink.jar
    # expose:
    #   - "2333"
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    # expose: # use if you want access from other machine
    #   - "5432"
  bot:
    build: .
    depends_on:
      - db
      - lavalink
    command: python3 main.py