services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  lavalink:
    build: lavalink_server
    command: java -jar Lavalink.jar
    volumes:
      - ./data/lavalink:/opt/Lavalink/logs
  bot:
    build: .
    depends_on:
      - db
      - lavalink
    command: python3 main.py