services:
  lavalink:
    build: lavalink_server
    restart: always
    ports:
      - "2333"
    volumes:
      - ./data/lavalink:/opt/Lavalink/logs
  bot:
    build: .
    restart: always
    volumes:
      - ./bot/cogs:/app/bot/cogs
    depends_on:
      - db
      - lavalink
      - mongo
    command: python3 main.py
  redis_prefixes:
    image: redis
    restart: always
    volumes:
      - ./data/redis_prefixes:/data
  nyalink_cache:
    image: redis
    restart: always
    volumes:
      - ./data/nyalink_cache:/data
  nya_link:
    build: ./koklin
    restart: always
    ports:
      - "8000"
    environment:
      PORT: 8000
      REDIS_PORT: 6379
      REDIS_URL: nyalink_cache
      TOKEN: sus