services:
  lavalink:
    build: lavalink_server
    restart: always
    ports:
      - "2333"
    volumes:
      - ./data/lavalink:/opt/Lavalink/logs
  bot:
    build: .
    restart: always
    volumes:
      - ./bot/cogs:/app/bot/cogs
    depends_on:
      - db
      - lavalink
      - mongo
    command: python3 main.py

  redis_prefixes:
    image: redis
    restart: always
    volumes:
      - ./data/redis_prefixes:/data
  nya_link:
    build: ./koklin
    restart: always
    ports:
      - "8000"
    environment:
      PORT: 8000
      REDIS_PORT: 6379
      REDIS_URL: host.docker.internal
      TOKEN: BQAPAgyxOAqRGocl0i58lKK2SC6x6oGwt3wJbCVGP3-S0e9-EV3HPJpiFpcyYnJPJ9sw49XsYzbyn95wzDAYSq_SfQCK8a9zJV8P-ZEah5MViVuMsEUIcj9rzbrXFWgTXrExmIFW2Njwq_CU8Tyff9zCg_GBUrH6FqLHt9MUy5P8sHEFTBphbBODQzbVUQQeAmek2EYCaKpwNaOqZyWgbUQVlb4N